# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "pygame","main" ]
  pull_request:
    branches: [ "pygame","main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
       # stop the build if there are Python syntax errors or undefined names
       flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
       # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
       flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  release:
    name: release-project
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      actions: read
    steps:
      - name: Create release zip
        run: zip -r DDDeepWeb.zip . -i .
        if: success()

      - name: Create Release 
        if: github.ref == 'refs/heads/pygame'
        # uses: actions/create-release@v1
        # uses: softprops/action-gh-release@v1
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        # with:
        #   tag_name: v1.0.${{ github.run_number }}
        #   name: V1.0.${{ github.run_number }}
        #   prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          gh release create ${{ github.ref_name }}
          "DDDeepWeb.zip"
          --generate-notes
          --title "Version ${{ github.ref_name }}"

